dependencies:
  - python=3.5
  - pip:
    - ipykernel
    - scipy
    - scikit-learn
    - tensorflow
    - matplotlib
    - seaborn
    - pandas
    - thinc
    - sympy
    - nltk
    - gensim    
    - spacy
